import{a as y,S as p,i as L}from"./assets/vendor-b0d10f48.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&o(h)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const w="43983774-8711aa48aacb0ae1050be5e44";async function m(t,r=1,a=15){const o=`https://pixabay.com/api/?key=${w}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${a}`;try{return(await y.get(o)).data.hits}catch(e){throw console.error("Error fetching images:",e.message),e}}function v(){const t=document.querySelector(".gallery");t.innerHTML=""}function f(t){const r=document.querySelector(".gallery"),a=t.map(o=>`
        <a href="${o.largeImageURL}" data-lightbox="gallery">
            <div class="card">
                <img src="${o.webformatURL}" alt="${o.tags}">
                <div class="card-details">
                    <p>Likes: ${o.likes}</p>
                    <p>Views: ${o.views}</p>
                    <p>Comments: ${o.comments}</p>
                    <p>Downloads: ${o.downloads}</p>
                </div>
            </div>
        </a>
    `).join("");r.insertAdjacentHTML("beforeend",a)}const b=document.getElementById("searchForm"),u=document.getElementById("searchInput"),i=document.querySelector(".loader");document.querySelector(".gallery");const l=document.getElementById("loadMoreBtn"),g=new p(".gallery a");let c="",d=1;function n(t){L.error({title:"Error",message:t,position:"topRight"})}function E(){const a=document.querySelector(".gallery a:last-child").getBoundingClientRect().height*2;window.scrollBy({top:a,left:0,behavior:"smooth"})}async function $(){i.classList.add("show"),d++;try{const t=await m(c,d);t.length===0?(l.classList.add("hidden"),n("We're sorry, but you've reached the end of search results.")):(f(t),g.refresh(),E())}catch(t){console.error("Error fetching images:",t.message),n("Failed to fetch more images. Please try again later.")}finally{i.classList.remove("show")}}async function I(t){if(t.preventDefault(),c=u.value.trim(),!c){n("Please enter a search term");return}i.classList.add("show"),v();try{d=1;const r=await m(c,d);r.length===0?(n("We`re sorry, but you`ve reached the end of search results."),l.classList.add("hidden")):(f(r),u.value="",g.refresh(),l.classList.remove("hidden"))}catch(r){console.error("Error fetching images:",r.message),n("Failed to fetch images. Please try again later.")}finally{i.classList.remove("show")}}l.addEventListener("click",$);b.addEventListener("submit",I);
//# sourceMappingURL=commonHelpers.js.map
