import{a as y,S as p,i as L}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&s(m)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const v="43983774-8711aa48aacb0ae1050be5e44";async function h(r,t=1,a=15){const s=`https://pixabay.com/api/?key=${v}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${a}`;try{return(await y.get(s)).data.hits}catch(e){throw console.error("Error fetching images:",e.message),e}}function w(){const r=document.querySelector(".gallery");r.innerHTML=""}function g(r){const t=document.querySelector(".gallery"),a=r.map(s=>`
        <a href="${s.largeImageURL}" data-lightbox="gallery">
            <div class="card">
                <img src="${s.webformatURL}" alt="${s.tags}">
                <div class="card-details">
                    <p>Likes: ${s.likes}</p>
                    <p>Views: ${s.views}</p>
                    <p>Comments: ${s.comments}</p>
                    <p>Downloads: ${s.downloads}</p>
                </div>
            </div>
        </a>
    `).join("");t.insertAdjacentHTML("beforeend",a)}const b=document.getElementById("searchForm"),u=document.getElementById("searchInput"),n=document.querySelector(".loader"),E=document.querySelector(".gallery"),l=document.getElementById("loadMoreBtn"),f=new p(".gallery a");let c="",d=1;function i(r){L.error({title:"Error",message:r,position:"topRight"})}async function $(){n.classList.add("show"),d++;try{const r=await h(c,d);if(r.length===0)i("We're sorry, but you've reached the end of search results.");else{g(r),f.refresh(),l.classList.add("hidden");const t=E.getBoundingClientRect().height;window.scrollBy({top:1100,behavior:"smooth"})}}catch(r){console.error("Error fetching images:",r.message),i("Failed to fetch more images. Please try again later.")}finally{n.classList.remove("show")}}l.addEventListener("click",$);b.addEventListener("submit",async r=>{if(r.preventDefault(),c=u.value.trim(),!c){i("Please enter a search term");return}n.classList.add("show"),w();try{d=1;const t=await h(c,d);n.classList.remove("show"),t.length===0?(i("Sorry, there are no images matching your search query. Please try again!"),l.classList.remove("hidden")):(g(t),u.value="",f.refresh(),l.classList.remove("hidden"))}catch(t){n.classList.remove("show"),console.error("Error fetching images:",t.message),i("Failed to fetch images. Please try again later.")}});
//# sourceMappingURL=commonHelpers.js.map
